name: Deploy Project

on:
  push:
    branches:
      - main  # Trigger the action on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The machine on which the workflow will run

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # This will clone the repo to the runner

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the Node version you need for your project

    - name: Install dependencies
      run: npm install  # Installs the dependencies from package.json

    - name: Build the project
      run: npm run build  # This assumes you have a build script in your package.json

    - name: Deploy to GitHub Pages (or other platform)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Token provided automatically by GitHub
        publish_dir: ./build  # Change to the directory where the build files are located
